version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=mi_base_de_datos
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=contraseña

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mi_base_de_datos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
      MYSQL_ROOT_PASSWORD: contraseña_root
    volumes:
      - mysql-data:/var/lib/mysql
    # Remueve esta línea si no quieres exponer MySQL fuera del contenedor
    # - "3306:3306"

volumes:
  mysql-data:
